package com.project.urlShortener.Model;


import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import com.project.urlShortener.Constants.Constants;
import com.project.urlShortener.Enum.AllowedCategories;

//adicionar no cloudformation

@DynamoDBTable(tableName = Constants.CATEGORIES_TABLE_NAME)
public class Categories {
    @DynamoDBAutoGeneratedKey
    private Integer categoryId;
    @DynamoDBAttribute
    private AllowedCategories category;

    @DynamoDBAttribute
    private Integer amount;

    @DynamoDBHashKey
    public AllowedCategories getCategory() {
        return category;
    }

    public Integer getCategoryId() {
        return categoryId;
    }

    public void setCategoryId(Integer categoryId) {
        this.categoryId = categoryId;
    }

    public void setCategory(AllowedCategories category) {
        this.category = category;
    }

    public int getAmount() {
        return amount;
    }

    public void setAmount(Integer amount) {
        this.amount = amount;
    }
}
