package com.project.urlShortener.Model;

import com.amazonaws.services.dynamodbv2.datamodeling.*;

@DynamoDBTable(tableName = "DynamoDbUrlTable")
public class Url {

    @DynamoDBAutoGeneratedKey
    private Integer urlId;

    @DynamoDBAttribute
    private String longUrl;

    @DynamoDBAttribute
    private String shortUrl;

    @DynamoDBAttribute
    private Integer clicks;

    @DynamoDBAttribute
    private Integer ttl;

    @DynamoDBAttribute
    private Boolean active;

    //colocar createdAt e fazer logica com o ttl para expirar o link

    public Boolean getActive() {
        return active;
    }

    public void setActive(Boolean active) {
        this.active = active;
    }
    @DynamoDBHashKey
    public Integer getUrlId() {
        return urlId;
    }

    public void setUrlId(Integer urlId) {
        this.urlId = urlId;
    }

    @DynamoDBRangeKey
    public String getLongUrl() {
        return longUrl;
    }

    public void setLongUrl(String longUrl) {
        this.longUrl = longUrl;
    }

    public String getShortUrl() {
        return shortUrl;
    }

    public void setShortUrl(String shortUrl) {
        this.shortUrl = shortUrl;
    }

    public Integer getClicks() {
        return clicks;
    }

    public void setClicks(Integer clicks) {
        this.clicks = clicks;
    }

    public Integer getTtl() {
        return ttl;
    }

    public void setTtl(Integer ttl) {
        this.ttl = ttl;
    }
}
