AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: A backend with a Restful Api endpoint using amazon API Gateway
Resources:
  GetUrlLambda:
    Type: 'AWS::Serverless::Function'
    Properties:
      Description: This lambda gets a register of url from DynamoDb
      Handler: url.get.lambda.LambdaMethodHandler::handlerRequest
      FunctionName: get-url
      Runtime: java8
      CodeUri: s3://get-url-code-for-lambda-function/project.urlShortener-1.0-SNAPSHOT.jar
      Timeout: 5
      Policies:
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - 'dynamodb:DeleteItem'
                - 'dynamodb:GetItem'
                - 'dynamodb:PutItem'
                - 'dynamodb:UpdateItem'
              Resource:
                'Fn::Join':
                  - ''
                  - - 'arn:aws:dynamodb:'
                    - Ref: 'AWS::Region'
                    - ':'
                    - Ref: 'AWS::AccountId'
                    - ':table/DynamoDbUrlTable'
      Events:
        GetAllMethod:
          Type: Api
          Properties:
            Path: /get/url
            Method: Get
        GetSingleMethod:
          Type: Api
          Properties:
            Path: /get/{url}
            Method: Get
        PostMethod:
          Type: Api
          Properties:
            Path: /post/url
            Method: Post
        UpdateMethod:
          Type: Api
          Properties:
            Path: /update/{url}
            Method: Put
        DeleteMethod:
          Type: Api
          Properties:
            Path: /delete/{url}
            Method: Put

  DynamoDbUrlTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: "DynamoDbUrlTable"
      AttributeDefinitions:
        - AttributeName: "id"
          AttributeType: "S"
        - AttributeName: "longUrl"
          AttributeType: "S"
          #Add gsi later
      KeySchema:
        - AttributeName: "id"
          KeyType: "HASH"
        - AttributeName: "longUrl"
          KeyType: "RANGE"

      ProvisionedThroughput:
        ReadCapacityUnits: "5"
        WriteCapacityUnits: "5"