AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: A backend with a Restful Api endpoint using amazon API Gateway
Resources:
  GetUrlLambda:
    Type: 'AWS::Serverless::Function'
    Properties:
      Description: This lambda gets a register of url from DynamoDb
      Handler: com.project.urlShortener.Gateway.LambdaMethodHandler::handleRequest
      FunctionName: lambda-controller
      Runtime: java8
      CodeUri: s3://get-url-code-for-lambda-function/project.urlShortener-1.0-SNAPSHOT.jar
      Timeout: 5
      Policies:
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - 'dynamodb:DeleteItem'
                - 'dynamodb:GetItem'
                - 'dynamodb:PutItem'
                - 'dynamodb:UpdateItem'
              Resource:
                'Fn::Join':
                  - ''
                  - - 'arn:aws:dynamodb:'
                    - Ref: 'AWS::Region'
                    - ':'
                    - Ref: 'AWS::AccountId'
                    - ':table/DynamoDbUrlTable'
      Events:
        #Refactor paths and methods later
        GetAllMethod:
          Type: Api
          Properties:
            Path: /get/url
            Method: Get
        GetSingleMethod:
          Type: Api
          Properties:
            Path: /get/{url}
            Method: Get
        PopulateDatabase:
          Type: Api
          Properties:
            Path: /populate
            Method: Post
        PostMethod:
          Type: Api
          Properties:
            Path: /post/url
            Method: Post
        UpdateMethod:
          Type: Api
          Properties:
            Path: /update/{url}
            Method: Put
        DeleteMethod:
          Type: Api
          Properties:
            Path: /delete/{url}
            Method: Delete

  DynamoDbUrlTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: "DynamoDbUrlTable"
      AttributeDefinitions:
        - AttributeName: "urlId"
          AttributeType: "N"
        - AttributeName: "longUrl"
          AttributeType: "S"
          #Add gsi later
      KeySchema:
        - AttributeName: "urlId"
          KeyType: "HASH"
        - AttributeName: "longUrl"
          KeyType: "RANGE"

      ProvisionedThroughput:
        ReadCapacityUnits: "5"
        WriteCapacityUnits: "5"


 #finalizar config tabela de categories

#  Categories:
#    Type: AWS::DynamoDB::Table
#    Properties:
#      TableName: "DynamoDbUrlTable"
#      AttributeDefinitions:
#        - AttributeName: "urlId"
#          AttributeType: "N"
#      KeySchema:
#        - AttributeName: "urlId"
#          KeyType: "HASH"
#        - AttributeName: "longUrl"
#          KeyType: "RANGE"
#
#      ProvisionedThroughput:
#        ReadCapacityUnits: "5"
#        WriteCapacityUnits: "5"